language: node_js
node_js:
  - "6"
notifications:
  webhooks: https://outlook.office.com/webhook/6ffa3ce3-679d-4fc8-bdad-8bc2f2d3d69e@e3cf3c98-a978-465f-8254-9d541eeea73c/TravisCI/1fd4fea84dde4e7783dbebafb2d1a7e0/0e17a87e-262a-4a59-9224-5e6b08e0eccd
  on_success: change # default: always
  on_failure: always # default: always
  on_start: change   # default: never
  on_cancel: always # default: always
  on_error: always # default: always