//import css file to inject it into html file generated by webpack
import './index.css';
import {getUsers} from "./api/userApi";
//import numeral from 'numeral';

//populate table of users via API call. In reality you would use Angular or React
getUsers().then(result =>{
    let userBody ="";

    result.forEach(user=>{
       userBody+=`<tr>
            <td><a href="#" data-id="${user.id}" class="deleteUser">Delete</a></td>
            <td>${user.id}</td>
            <td>${user.firstName}</td>
            <td>${user.lastName}</td>
            <td>${user.email}</td>
            </tr>`
    });

    global.document.getElementById('users').innerHTML =  userBody;

});


//ensures linting errors for console are not shown
/* eslint-disable no-console */

//const courseValue =  numeral(1000).format('$0,0.00');
//console.log(`I would pay ${courseValue} for this awesome course!`);
