//import css file to inject it into html file generated by webpack
import './index.css';
import numeral from 'numeral';

//ensures linting errors for console are not shown
/* eslint-disable no-console */

const courseValue =  numeral(1000).format('$0,0.00');
console.log(`I would pay ${courseValue} for this awesome course!`);
